lib/fruit_picker_web/router.ex
defmodule FruitPickerWeb.Router do
  use FruitPickerWeb, :router
  use Plug.ErrorHandler
  use Sentry.Plug

  alias FruitPickerWeb.{
    Plugs,
    Policies,
    LayoutView
  }

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(Plugs.Auth, repo: Repo)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :authenticated do
    plug(Policies, :current_person)
    plug(:put_layout, {LayoutView, :authenticated})
  end

  pipeline :admin do
    plug(Policies, :is_admin)
  end

  pipeline :tree_owner do
    plug(Policies, :is_tree_owner)
    plug(Policies, :waiver_consent_tree_owner)
  end

  pipeline :lead_picker do
    plug(Policies, :is_lead_picker)
  end

  pipeline :agency do
    plug(Policies, :is_agency)
  end

  pipeline :picker do
    plug(Policies, :not_agency)
    plug(Policies, :waiver_consent_picker)
  end

  pipeline :membership do
    plug(Policies, :active_membership)
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :webhook do
    plug :accepts, ["json"]
  end

  if Mix.env() == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end

  scope "/admin", FruitPickerWeb.Admin, as: :admin do
    pipe_through([
      :browser,
      :authenticated,
      :admin
    ])

    resources("/picks", PickController, except: [:delete])
    resources("/partners", AgencyController)
    resources("/equipment", EquipmentSetController)
    resources("/users", PersonController)
    get("/reports", ReportController, :index)
    resources("/reports/attendance", ReportAttendanceController, only: [:new, :create])
    get("/equipment/:id/activate", EquipmentSetController, :activate)
    get("/equipment/:id/deactivate", EquipmentSetController, :deactivate)
    get("/picks/:pick_id/activate", PickController, :request_activate)
    put("/picks/:pick_id/activate", PickController, :activate)
    get("/picks/:pick_id/cancel", PickController, :request_cancel)
    get("/picks/:pick_id/make_private", PickController, :make_private)
    get("/picks/:pick_id/assign_lead_picker", PickController, :assign_lead_picker)
    put("/picks/:pick_id/cancel", PickController, :cancel)
    get("/picks/:pick_id/reschedule", PickController, :request_reschedule)
    put("/picks/:pick_id/reschedule", PickController, :reschedule)
    get("/picks/:pick_id/claim", PickController, :request_claim)
    put("/picks/:pick_id/claim", PickController, :claim)
    get("/picks/:pick_id/report", PickReportController, :new)
    post("/picks/:pick_id/report", PickReportController, :create)
    get("/picks/:pick_id/report/fruit", PickReportController, :fruit)
    put("/picks/:pick_id/report/fruit", PickReportController, :report_fruit)
    delete("/picks/:pick_id", PickController, :delete)
    put("/picks/:pick_id/remove_lead_picker", PickController, :remove_lead_picker)
    delete("/picks/:pick_id/remove/:person_id", PickController, :remove_picker)
    get("/picks/:pick_id/edit_pick_report", PickController, :edit_pick_report)
    get("/picks/:pick_id/edit_pick_attendance", PickController, :edit_pick_attendance)
    put("/picks/:pick_id/edit_pick_attendance", PickController, :update_pick_attendance)
    get("/picks/:pick_id/edit_pick_fruits", PickController, :edit_pick_fruits)
    put("/picks/:pick_id/edit_pick_fruits", PickController, :update_pick_fruits)
    post("/users/:id", PersonController, :deactivate)
    get("/users/:id/payment", PaymentController, :new)
    post("/users/:id/payment", PaymentController, :create)
    get("/users/:id/stats", PersonController, :stats)
    get("/users/:id/property", PropertyController, :show)
    get("/users/:id/property/setup", PropertyController, :setup)
    put("/users/:id/property", PropertyController, :update)
    post("/users/:id/property", PropertyController, :create)
    get("/users/:id/property/edit", PropertyController, :edit)
    get("/users/:id/request_pick", RequestPickController, :new)
    post("/users/:id/request_pick", RequestPickController, :create)
    get("/users/:user_id/trees/:tree_id", TreeController, :show)
    put("/users/:user_id/trees/:tree_id", TreeController, :update)
    get("/users/:user_id/trees/:tree_id/edit", TreeController, :edit)
    get("/users/:user_id/trees/:tree_id/deactivate", TreeController, :request_deactivate)
    put("/users/:user_id/trees/:tree_id/deactivate", TreeController, :deactivate)
  end

  # Tree owner
  scope "/", FruitPickerWeb do
    pipe_through([
      :browser,
      :authenticated,
      :tree_owner
    ])

    get("/property", PropertyController, :index)
    get("/property/setup", PropertyController, :new)
    post("/property/setup", PropertyController, :create)
    get("/property/edit", PropertyController, :edit)
    put("/property/edit", PropertyController, :update)
    resources("/trees", TreeController, except: [:index, :delete])
    get("/trees", PropertyController, :index)
    get("/trees/:id/deactivate", TreeController, :request_deactivate)
    put("/trees/:id/deactivate", TreeController, :deactivate)
  end

  # Tree owner (paid)
  scope "/", FruitPickerWeb do
    pipe_through([
      :browser,
      :authenticated,
      :membership,
      :tree_owner
    ])

    get("/trees/:id/deactivate", TreeController, :request_deactivate)
    put("/trees/:id/deactivate", TreeController, :deactivate)
    resources("/picks", PickController, except: [:index, :delete, :show])
    get("/picks/:pick_id/tree_update", PickController, :next_tree)
    get("/picks/:pick_id/tree_update/:tree_id", PickController, :tree_info)
    post("/picks/:pick_id/tree_update/:tree_id", PickController, :tree_update)
    get("/picks/:pick_id/confirm_details", PickController, :confirm_details)
    put("/picks/:pick_id/confirm_details", PickController, :update_details)
    get("/picks/:pick_id/thank_you", PickController, :thank_you)
    get("/picks/:pick_id/reschedule", PickController, :request_reschedule)
    put("/picks/:pick_id/reschedule", PickController, :reschedule)
    get("/picks/:pick_id/cancel", PickController, :request_cancel)
    put("/picks/:pick_id/cancel", PickController, :cancel)
  end

  # Lead Pickers
  scope "/", FruitPickerWeb do
    pipe_through([
      :browser,
      :authenticated,
      :lead_picker
    ])

    get("/picks/:pick_id/claim", PickController, :request_claim)
    put("/picks/:pick_id/claim", PickController, :claim)
    get("/picks/:pick_id/report", PickReportController, :new)
    post("/picks/:pick_id/report", PickReportController, :create)
    get("/picks/:pick_id/report/fruit", PickReportController, :fruit)
    put("/picks/:pick_id/report/fruit", PickReportController, :report_fruit)
  end

  scope "/", FruitPickerWeb do
    pipe_through([
      :browser,
      :authenticated,
      :agency
    ])
  end

  # Volunteers (not agency partners)
  scope "/", FruitPickerWeb do
    pipe_through([
      :browser,
      :authenticated,
      :picker,
      :membership
    ])

    resources("/picks", PickController, only: [:show])
    get("/picks/:pick_id/join", PickController, :request_join)
    put("/picks/:pick_id/join", PickController, :join)
    get("/picks/:pick_id/leave", PickController, :leave)
    put("/picks/:pick_id/leave", PickController, :leave)
  end

  # Logged in users
  scope "/", FruitPickerWeb do
    pipe_through([:browser, :authenticated])

    resources("/agency", AgencyController)
    get("/my_agency", AgencyController, :mine)
    get("/", DashboardController, :index)
    get("/profile", ProfileController, :show)
    get("/profile/edit", ProfileController, :edit)
    get("/profile/setup", ProfileController, :setup)
    put("/profile", ProfileController, :update)
    get("/profile/avatar", AvatarController, :edit)
    put("/profile/avatar", AvatarController, :update)
    get("/profile/payment", ProfileController, :payment_thanks)
    delete("/profile/avatar/:id", AvatarController, :delete)
    get("/stats", StatsController, :index)
  end

  # Public to all
  scope "/", FruitPickerWeb do
    pipe_through :browser

    get("/donate", DonationController, :index)
    get("/register", RegisterController, :new)
    post("/register", RegisterController, :create)
    get("/signin", AuthController, :request)
    post("/signin", AuthController, :signin)
    delete("/signout/:id", AuthController, :signout)
    get("/password-reset", AuthController, :forgot)
    post("/password-reset", AuthController, :forgot_request)
    get("/password-reset/:token_value", AuthController, :new_password)
    post("/password-reset/:token_value", AuthController, :create_password)
    put("/password-reset/:token_value", AuthController, :create_password)
  end

  scope "/webhooks", FruitPickerWeb do
    pipe_through :webhook

    post("/stripe", WebhookController, :create)
  end

  # Other scopes may use custom stacks.
  # scope "/api", FruitPickerWeb do
  #   pipe_through :api
  # end
end

lib/fruit_picker_web/controllers/admin/agency_controller.ex
defmodule FruitPickerWeb.Admin.AgencyController do
  use FruitPickerWeb, :controller

  alias FruitPicker.Partners
  alias FruitPicker.Partners.{Agency}
  alias FruitPickerWeb.Policies

  plug(Policies, :is_admin)

  def index(conn, params) do
    page_num = Map.get(params, "page", "1")
    sort_by = Map.get(params, "sort_by")
    desc = Map.get(params, "desc")
    page = Partners.list_agencies(page_num, sort_by, desc)

    render(conn, "index.html",
      page: page,
      agencies: page.entries,
      agencies_count: page.total_entries,
      sort_by: sort_by,
      desc: desc
    )
  end

  def new(conn, _params) do
    changeset = Partners.change_agency(%Agency{})
    available_people = available_with_current(nil)

    render(conn, "new.html",
      changeset: changeset,
      available_people: available_people,
      action_name: "Add"
    )
  end

  def create(conn, %{"agency" => agency_params}) do
    case Partners.create_agency(agency_params) do
      {:ok, agency} ->
        conn
        |> put_flash(:success, "The Agency " <> agency.name <> " was created successfully.")
        |> redirect(to: Routes.admin_agency_path(conn, :show, agency))
      {:error, %Ecto.Changeset{} = changeset} ->
        available_people = available_with_current(nil)

        conn
        |> put_flash(:error, "There was a problem creating the agency.")
        |> render(
          "new.html",
          changeset: changeset,
          available_people: available_people,
          action_name: "Add"
        )
    end
  end

  def show(conn, %{"id" => id}) do
    agency = Partners.get_agency!(id)
    scheduled_picks = Partners.get_scheduled_picks(agency)
    completed_picks = Partners.get_completed_picks(agency)
    render(conn, "show.html",
      agency: agency,
      scheduled_picks: scheduled_picks,
      completed_picks: completed_picks
    )
  end

  def edit(conn, %{"id" => id}) do
    agency = Partners.get_agency!(id)
    current_partner = agency.partner
    available_people = available_with_current(current_partner)
    changeset = Partners.change_agency(agency)
    render(
      conn,
      "edit.html",
      agency: agency,
      available_people: available_people,
      changeset: changeset,
      action_name: "Update"
    )
  end

  def update(conn, %{"id" => id, "agency" => agency_params}) do
    agency = Partners.get_agency!(id)
    current_partner = agency.partner

    case Partners.update_agency(agency, agency_params) do
      {:ok, agency} ->
        conn
        |> put_flash(:info, "Agency updated successfully.")
        |> redirect(to: Routes.admin_agency_path(conn, :show, agency))

      {:error, %Ecto.Changeset{} = changeset} ->
        available_people = available_with_current(current_partner)

        render(
          conn,
          "edit.html",
          agency: agency,
          available_people: available_people,
          changeset: changeset,
          action_name: "Update"
        )
    end
  end

  def delete(conn, %{"id" => id}) do
    agency = Partners.get_agency!(id)
    {:ok, _agency} = Partners.delete_agency(agency)

    conn
    |> put_flash(:info, "Agency deleted successfully.")
    |> redirect(to: Routes.admin_agency_path(conn, :index))
  end

  def available_with_current(person) do
    if person do
      [person | Partners.get_available()]
    else
      Partners.get_available()
    end
  end
end

lib/fruit_picker_web/controllers/admin/equipment_set_controller.ex
defmodule FruitPickerWeb.Admin.EquipmentSetController do
  use FruitPickerWeb, :controller

  alias FruitPicker.Inventory
  alias FruitPicker.Inventory.{EquipmentSet}
  alias FruitPicker.Accounts.{Person, Profile}
  alias FruitPickerWeb.{PersonController, Policies}

  plug(Policies, :is_admin)

  def index(conn, params) do
    page_num = Map.get(params, "page", "1")
    sort_by = Map.get(params, "sort_by")
    desc = Map.get(params, "desc")
    page = Inventory.list_equipment_sets(page_num, sort_by, desc)

    render(conn, "index.html",
      page: page,
      equipment_sets: page.entries,
      equipment_sets_count: page.total_entries,
      sort_by: sort_by,
      desc: desc
    )
  end

  def new(conn, _params) do
    changeset = Inventory.change_equipment_set(%EquipmentSet{})
    render(conn, "new.html",
      changeset: changeset,
      action_name: "Add",
    )
  end

  def create(conn, %{"equipment_set" => equipment_set_params}) do
    case Inventory.create_equipment_set(equipment_set_params) do
      {:ok, equipment_set} ->
        conn
        |> put_flash(:success, "The Equipment Set " <> equipment_set.name <> " was created successfully.")
        |> redirect(to: Routes.admin_equipment_set_path(conn, :show, equipment_set))

      {:error, %Ecto.Changeset{} = changeset} ->
        conn
        |> put_flash(:error, "There was a problem creating the set.")
        |> render(
          "new.html",
          changeset: changeset,
          action_name: "Add",
        )
    end
  end

  def show(conn, %{"id" => id}) do
    equipment_set = Inventory.get_equipment_set!(id)
    scheduled_picks = Inventory.get_scheduled_picks(equipment_set)
    completed_picks = Inventory.get_completed_picks(equipment_set)
    render(conn, "show.html",
      equipment_set: equipment_set,
      scheduled_picks: scheduled_picks,
      completed_picks: completed_picks,
    )
  end

  def edit(conn, %{"id" => id}) do
    equipment_set = Inventory.get_equipment_set!(id)
    changeset = Inventory.change_equipment_set(equipment_set)
    render(
      conn,
      "edit.html",
      equipment_set: equipment_set,
      changeset: changeset,
      action_name: "Update",
    )
  end

  def update(conn, %{"id" => id, "equipment_set" => equipment_set_params}) do
    equipment_set = Inventory.get_equipment_set!(id)

    case Inventory.update_equipment_set(equipment_set, equipment_set_params) do
      {:ok, equipment_set} ->
        conn
        |> put_flash(:info, "Equipment Set updated successfully.")
        |> redirect(to: Routes.admin_equipment_set_path(conn, :show, equipment_set))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(
          conn,
          "edit.html",
          equipment_set: equipment_set,
          changeset: changeset,
          action_name: "Update"
        )
    end
  end

  def activate(conn, %{"id" => id}) do
    equipment_set = Inventory.get_equipment_set!(id)
    {:ok, _equipment_set} = Inventory.activate_equipment_set(equipment_set)

    conn
    |> put_flash(:info, "Equipment Set activated successfully.")
    |> redirect(to: Routes.admin_equipment_set_path(conn, :show, equipment_set))
  end

  def deactivate(conn, %{"id" => id}) do
    equipment_set = Inventory.get_equipment_set!(id)
    {:ok, _equipment_set} = Inventory.deactivate_equipment_set(equipment_set)

    conn
    |> put_flash(:info, "Equipment Set deactivated successfully.")
    |> redirect(to: Routes.admin_equipment_set_path(conn, :show, equipment_set))
  end

  def delete(conn, %{"id" => id}) do
    equipment_set = Inventory.get_equipment_set!(id)
    {:ok, _equipment_set} = Inventory.delete_equipment_set(equipment_set)

    conn
    |> put_flash(:info, "Equipment Set deleted successfully.")
    |> redirect(to: Routes.admin_equipment_set_path(conn, :index))
  end
end

lib/fruit_picker_web/controllers/admin/payment_controller.ex
defmodule FruitPickerWeb.Admin.PaymentController do
  @moduledoc false

  use FruitPickerWeb, :controller

  alias FruitPicker.{Mailer, Repo}
  alias FruitPicker.Accounts
  alias FruitPicker.Accounts.{
    Person,
    Tree,
    TreeSnapshot
  }
  alias FruitPicker.Accounts.MembershipPayment

  def new(conn, %{"id" => id}) do
    person = Accounts.get_person!(id)

    changeset = MembershipPayment.changeset(%MembershipPayment{}, %{})
    render(conn, "new.html",
      person: person,
      changeset: changeset,
    )
  end

  def create(conn, %{"membership_payment" => payment_params, "id" => id}) do
    person = Accounts.get_person!(id)

    case Accounts.create_payment(payment_params, person) do
      {:ok, %{payment: payment, person: person}} ->
        conn
        |> put_flash(:success, "The payment was created successfully.")
        |> redirect(to: Routes.admin_person_path(conn, :show, person))

      {:error, %Ecto.Changeset{} = changeset} ->
        person = Accounts.get_person!(id)

        conn
        |> put_flash(:error, "There was a problem creating the payment.")
        |> render(
          "new.html",
          person: person,
          changeset: changeset
        )
    end
  end
end

lib/fruit_picker_web/controllers/donation_controller.ex
defmodule FruitPickerWeb.DonationController do
  use FruitPickerWeb, :controller

  alias FruitPicker.Accounts
  alias FruitPicker.Accounts.Donation

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/fruit_picker_web/live/assign_lead_picker_live.html.leex
<%= f = form_for @changeset, "#", [phx_change: :change, phx_submit: :submit] %>
<label class="flex flex-column mb4 w-50-l w-100" >
  <span class="dark-gray pointer mb2">Pick Date</span>
  <%= date_input f, :scheduled_date, placeholder: Date.utc_today(),
class: "input-reset flex justify-center h50px ph3 br2 ba br0 bg-white b--light-gray pointer"
        %>
        <%= error_tag f, :scheduled_date %>
</label>

<div class="flex flex-wrap flex-nowrap-l mw-40">
  <label class="flex flex-column mb4 w-100 w-50-l mr2-l">
    <span class="dark-gray pointer mb2">Pick Start Time</span>
    <div class="select-wrapper relative w-100">
      <%= select f, :scheduled_start_time, 
FruitPickerWeb.PickView.schedule_pick_available_hours(@pick, :start),
prompt: "Select Time",
class: "input-reset flex justify-center h50px ph3 br2 ba br0 bg-white b--light-gray w-100"
    %>
    <div class="absolute top-0 bottom-0 right-1 flex flex-column justify-center no-pointer">
      <%= Brady.inline_svg("icons/arrow", class: "w30px light-gray") %>
    </div>
    </div>
    <%= error_tag f, :scheduled_start_time %>
  </label>

  <label class="flex flex-column mb4 w-100 w-50-l ml2-l">
    <span class="dark-gray pointer mb2">Pick End Time</span>
    <p class="light-gray pt1 mv2 lh-copy">
      <%= if @scheduled_end_time do %>
        <%= @scheduled_end_time %>
      <% else %>
        Select a start time&hellip;
      <% end %>
    </p>
  </label>
</div>

  <label class="flex flex-column mb4 w-100">
    <span class="dark-gray pointer mb2">Equipment Set</span>
    <div class="select-wrapper relative w-100">
      <%= select f, :equipment_set_id, 
        @equipment_sets,
        prompt: "Select Equipment",
        class:  "input-reset flex justify-center h50px ph3 br2 ba br0 bg-white b--light-gray w-100"
      %>
      <div class="absolute top-0 bottom-0 right-1 flex flex-column justify-center no-pointer">
        <%= Brady.inline_svg("icons/arrow", class: "w30px light-gray") %>
      </div>
    </div>
    <%= error_tag f, :equipment_set_id %>
  </label>

  <label class="flex flex-column mb4 w-100">
    <span class="dark-gray pointer mb2">Agency</span>
    <div class="select-wrapper relative w-100">
      <%= select f, :agency_id, 
        @agencies,
        prompt: "Select Agency",
        class:  "input-reset flex justify-center h50px ph3 br2 ba br0 bg-white b--light-gray w-100"
      %>
      <div class="absolute top-0 bottom-0 right-1 flex flex-column justify-center no-pointer">
        <%= Brady.inline_svg("icons/arrow", class: "w30px light-gray") %>
      </div>
    </div>
    <%= error_tag f, :agency_id %>
  </label>
  <label class="flex flex-column mb4 w-100">
    <span class="dark-gray pointer mb2">Lead Picker</span>
    <div class="select-wrapper relative w-100">
      <%= select f, :lead_picker_id, 
        @lead_pickers,
        prompt: "Select Lead Picker",
        class:  "input-reset flex justify-center h50px ph3 br2 ba br0 bg-white b--light-gray w-100"
      %>
      <div class="absolute top-0 bottom-0 right-1 flex flex-column justify-center no-pointer">
        <%= Brady.inline_svg("icons/arrow", class: "w30px light-gray") %>
      </div>
    </div>
    <%= error_tag f, :lead_picker_id %>
  </label>
    <div class="flex justify-between items-center pb4">
      <%= submit "Schedule Pick", class: "input-reset small-button ml-auto br2 bg-green hover-bg-dark-green white tc bn flex justify-center items-center pointer", data: [confirm: "Please confirm that the pick information is correct and this pick is ready to be activated."]
    %>
    </div>
</form>

lib/fruit_picker_web/live/assign_pickers_live.html.leex
<section class="mv4">
  <h6 class="f5 normal mt0 mb2">Pickers</h6>
  <div class="b fw6 f1">
    <%= length(@pick.pickers) %>/<%= @pick.volunteers_max || 5 %>
  </div>
  <%= for picker <- @pick.pickers do %>
    <div class="fw3 mv0 lh-copy near-white flex w-100 items-center">
      <div class="w-40">
        <%= link("#{picker.first_name} #{picker.last_name}", to: Routes.admin_person_path(@socket, :show, picker), class: "link near-white hover-green") %>
      </div>
      <div class="w-40">
        <%= picker.profile.phone_number %>
      </div>
      <%= if @pick.status != :completed do %>
        <div class="w-10">
          <%= link(Brady.inline_svg("icons/cancel", height: "16px", width: "16px", alt: "remove"), to: Routes.admin_pick_path(@socket, :remove_picker, @pick, picker), class: "link w20px h20px bg-red white hover-black flex items-center justify-center br-pill", method: :delete, data: [confirm: "Are you sure you want to remove this picker?"]) %>
        </div>
      <% end %>
    </div>
  <% end %>
  <div class="mt4">
    <%= if length(@pick.pickers) < @pick.volunteers_max  do %>
      <%= f = form_for @changeset, "#", [phx_submit: :submit] %>
        <div class="flex br2 overflow-hidden">
          <label class="flex flex-column w-100">
            <div class="select-wrapper relative w-100">
              <%= select f, :id,
                @pickers,
                prompt: "Select Picker",
                class:  "input-reset flex justify-center h50px ph3 ba br0 bg-white b--light-gray w-100 br0"
              %>
              <div class="absolute top-0 bottom-0 right-1 flex flex-column justify-center no-pointer">
                <%= Brady.inline_svg("icons/arrow", class: "w30px light-gray") %>
              </div>
            </div>
            <%= error_tag f, :person_id %>
          </label>
          <button type="submit" class="bg-green white ph2 b--none hover-bg-dark-green pointer">Add</button>
        </div>
    <% end %>
    </div>
</section>

lib/fruit_picker_web/live/claim_live.html.leex
<%= f = form_for @changeset, Routes.pick_path(@socket, :claim, @pick), [phx_change: :change] %>
<label class="flex flex-column mb4 w-50-l w-100" >
  <span class="dark-gray pointer mb2">Pick Date</span>
  <%= date_input f, :scheduled_date, placeholder: Date.utc_today(),
class: "input-reset flex justify-center h50px ph3 br2 ba br0 bg-white b--light-gray pointer"
        %>
        <%= error_tag f, :scheduled_date %>
</label>

<div class="flex flex-wrap flex-nowrap-l mw-40">
  <label class="flex flex-column mb4 w-100 w-50-l mr2-l">
    <span class="dark-gray pointer mb2">Pick Start Time</span>
    <div class="select-wrapper relative w-100">
      <%= select f, :scheduled_start_time, 
FruitPickerWeb.PickView.schedule_pick_available_hours(@pick, :start),
prompt: "Select Time",
class: "input-reset flex justify-center h50px ph3 br2 ba br0 bg-white b--light-gray w-100"
    %>
    <div class="absolute top-0 bottom-0 right-1 flex flex-column justify-center no-pointer">
      <%= Brady.inline_svg("icons/arrow", class: "w30px light-gray") %>
    </div>
    </div>
    <%= error_tag f, :scheduled_start_time %>
  </label>

  <label class="flex flex-column mb4 w-100 w-50-l ml2-l">
    <span class="dark-gray pointer mb2">Pick End Time</span>
    <p class="light-gray pt1 mv2 lh-copy">
      <%= if @scheduled_end_time do %>
        <%= @scheduled_end_time %>
      <% else %>
        Select a start time&hellip;
      <% end %>
    </p>
  </label>
</div>

  <label class="flex flex-column mb4 w-100">
    <span class="dark-gray pointer mb2">Equipment Set</span>
    <div class="select-wrapper relative w-100">
      <%= select f, :equipment_set_id, 
        @equipment_sets,
        prompt: "Select Equipment",
        class:  "input-reset flex justify-center h50px ph3 br2 ba br0 bg-white b--light-gray w-100"
      %>
      <div class="absolute top-0 bottom-0 right-1 flex flex-column justify-center no-pointer">
        <%= Brady.inline_svg("icons/arrow", class: "w30px light-gray") %>
      </div>
    </div>
    <%= error_tag f, :equipment_set_id %>
  </label>

  <label class="flex flex-column mb4 w-100">
    <span class="dark-gray pointer mb2">Agency</span>
    <div class="select-wrapper relative w-100">
      <%= select f, :agency_id, 
        @agencies,
        prompt: "Select Agency",
        class:  "input-reset flex justify-center h50px ph3 br2 ba br0 bg-white b--light-gray w-100"
      %>
      <div class="absolute top-0 bottom-0 right-1 flex flex-column justify-center no-pointer">
        <%= Brady.inline_svg("icons/arrow", class: "w30px light-gray") %>
      </div>
    </div>
    <%= error_tag f, :agency_id %>
  </label>
    <div class="flex justify-between items-center pb4">
      <%= submit "Schedule Pick", class: "input-reset small-button ml-auto br2 bg-green hover-bg-dark-green white tc bn flex justify-center items-center pointer", data: [confirm: "Please confirm that the pick information is correct and this pick is ready to be activated."]
    %>
    </div>
</form>